# Generated by Django 4.0.3 on 2022-03-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitems',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='product',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
